### ISSUE TITLE
http://101.ru/?an=port_channel_mp3&channel=70

### ISSUE THREAD

**Issue by Lowbank** [roytanck/rocki-stream-player#3]
Hi  can you tell me why this URL will not work with ROCKI RADIO?
http://101.ru/?an=port_channel_mp3&channel=70
Cheer 
Jon

**Comment by roytanck** [comment]
From what I can tell, the URL is for a web page, not an audio stream. Looks like 101.ru does a good job hiding the actual stream URLs, and it seems they've secured them with keys.

Sometimes, the same station can be found on more than one website, so perhaps you can try to find one where the actual stream URL is visible in the page's source code?

**Comment by Lowbank** [comment]
Thanks for your reply. Looks like I just need to learn to recognise the right URL. Looks like they end with .pls or .asx
Cheers

**Comment by roytanck** [comment]
Stream URLs can also end simply in .mp3, and there are other options too. Best of luck!

**Comment by Lowbank** [comment]
HI Roy 

Thanks for your reply. Looks like I just need to learn to recognise the right URL. Looks like they end with .pls or .asx

 

I love the Idea of your Rocki Radio  is there any chance that you will further develop this as the “Rocki’s API is still a little rough around the edges” one year on.

 

Just need volume control and be able to add to Presets.

 

Cheers 

Jonathan Schmidt

 

Lowbank Services

www.lowbank.com.au

 <http://www.facebook.com/Lowbank.Services> facebook.com/Lowbank.Services

Mobile    0418 893 100

**Comment by roytanck** [comment]
Rocki are concentrating all their API efforts around UPnP. This perfectly fine, there are tons of apps out there that use UPnP, but it complicates things for my player. What started out as a simple web form would need to be converted into a full-blown javascript application just to control the volume.

I'll look into adding user presets. Do you use many stations? Perhaps I can even simply add yours to the player ;).
